on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Build package
    steps:
      - uses: actions/checkout@v1

      - name: Build package
        uses: mijailr/arch-makepkg-action@v1
